[tool.poetry]
name = "new-to-card_dev"
version = "0.0.5"
description = "Model new to card: identify customers who are likely to take up a credit card"
readme = "README.md"

packages = [
    { include = "new_to_card" },
    { include = "new_to_card_config" },
]

